<template>
  <vue-video-section
    :elementId="'header-background-video'"
    :ref="'header-background-video'"
    :mp4Source="require('../assets/videos/home.mp4')"
    :mobileBreakpoint="992"
    :desktopHeight="480"
    :mobileHeight="450"
    :playsinline="true"
    :loop="true"
    :autoplay="true"
    :autobuffer="true"
    :muted="true"
  ></vue-video-section>
</template>
